### ISSUE TITLE
Running on an Apple Device

### ISSUE THREAD

**Issue by Fireballion** [parthshah01/VeggieBuddie#3]
Hi @parthshah01 how do I run this on an apple device as it gives a warning with the pods file?

**Comment by helloparthshah** [comment]
This mostly happens when you upgrade your flutter application, to solve this issue follow the below steps:
Go to Your_Flutter_Project/ios/ and remove Podfile and Podfile.lock or you can do it by running the following command in the root project directory
rm ios/Podfile
Run your project again, this will create a new and updated Podfile for you.
Use pod install command in your ios directory to install new pods in your project. Even if you already have a Podfile and ran pod install before. This should work for you. I run into the same problem some time ago and
This is how it was solved.
cd Your_Flutter_Project/ios/
pod install
